### ISSUE TITLE
Serialize collection of resources

### ISSUE THREAD

**Issue by LeafyLappa** [MarkoMilos/jsonapi#5]
Hi!

How do I serialize collection of resources?

Here's what I'm trying:

```kotlin
override fun serializeMany(document: Document<*>): String {
    document as Document<List<AppResource>>
    return moshi.adapter<Document<List<AppResource>>>(AppResource::class.java).toJson(document)
}
```

I get this exception at runtime:
```
java.lang.IllegalArgumentException: A resource MUST contain non-null, non-empty type.
	at jsonapi.internal.ResourceBinder.readType(ResourceBinder.kt:55)
	at jsonapi.internal.ResourceBinder.readResourceObject(ResourceBinder.kt:34)
	at jsonapi.internal.adapter.ResourceTypeAdapter.toJson(ResourceTypeAdapter.kt:105)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
	at api.controller.AppsController.serializeMany(AppsController.kt:33)
	at api.controller.Controller.getMany(Controller.kt:15)
	at api.Router$route$2.invokeSuspend(Router.kt:37)
	at api.Router$route$2.invoke(Router.kt)
	at api.Router$route$2.invoke(Router.kt)
```

**Comment by LeafyLappa** [comment]
This might be a bug with serialization overall, I found that the function readType in ResourceBinder.kt is actually unable to get the type right for my adapter

**Comment by LeafyLappa** [comment]
I think I made it work by rewriting my function:
```kotlin
override fun serializeMany(document: Document<List<AppResource>>): String {
    return moshi.adapter<Document<List<AppResource>>>(typeOf<Document<List<AppResource>>>().javaType).toJson(document)
}
```
I wonder if there's a way to simplify that but it's really about Moshi so I'm closing this issue
